<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Clientes' => $baseDir . '/model/Clientes.class.php',
    'Conexao' => $baseDir . '/model/Conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'EasyPeasyICS' => $vendorDir . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
    'Empresa' => $baseDir . '/model/Empresa.class.php',
    'EnviarEmail' => $baseDir . '/model/EnviarEmail.class.php',
    'ImageUpload' => $baseDir . '/model/ImageUpload.class.php',
    'Login' => $baseDir . '/model/Login.class.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'PHPMailerOAuth' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'Paginacao' => $baseDir . '/model/Paginacao.class.php',
    'Pedidos' => $baseDir . '/model/Pedidos.class.php',
    'Portfolio' => $baseDir . '/model/Portfolio.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'Sistema' => $baseDir . '/model/Sistema.class.php',
    'Sobre' => $baseDir . '/model/Sobre.class.php',
    'Template' => $baseDir . '/model/Template.class.php',
    'User' => $baseDir . '/model/User.class.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
